version: "3.8"

services:
  db:
    container_name: okidocky-db
    image: clickhouse/clickhouse-server
    environment:
      - CLICKHOUSE_DB=my_database
      - CLICKHOUSE_USER=username
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=password
    networks:
      - main
    volumes:
      - ./clickhouse_db:/var/lib/clickhouse
    restart: always
    ports:
      - "9000:9000"
      - "9004:9004"
      - "8123:8123"
      - "9005:9005"

    #CLICKHOUSE_DB=my_database -e CLICKHOUSE_USER=username -e CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1 -e CLICKHOUSE_PASSWORD=password -p 5566:9000/tcp -p 8123:8123/tcp -d --name okidocky-clickhouse clickhouse/clickhouse-server

  core:
    container_name: okidocky-core
    privileged: true
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    restart: always
    network_mode: "host"
    # networks:
    #   - main
    # ports:
    #   - 8000:8000
    volumes:
      - "/:/rootfs:ro,rslave"
      - "/run/docker.sock:/run/docker.sock:ro,rslave"
      - "./back/target:/app/target"
      - "./back/src:/app/src"
      - "./back/bindings:/app/bindings"
      - "./sqlite_db:/app/sqlite"
      # - back:/opt/app
      # - /run/run/docker.sock:/var/run/docker.sock:ro


  ui:
    container_name: okidocky-ui
    build:
      context: ./front
    depends_on:
      - core
    restart: always
    network_mode: "host"
    # networks:
    #   - main
    # ports:
    #   - "7777:5173"
    volumes:
      - "./front/src:/opt/app/src"

  caddy:
    container_name: okidocky-caddy
    image: caddy:latest
    depends_on:
      - core
    restart: always
    network_mode: "host"
    # networks:
    #   - main
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - ./caddy_data:/data
      - ./caddy_config:/config
    # ports:
    #   - "80:80"
    #   - "443:443"
    # - "443:443/udp"


networks:
  main:
    driver: bridge