version: "3.3"

services:
  db:
    container_name: okidocky-db
    image: clickhouse/clickhouse-server
    environment:
      - CLICKHOUSE_DB=okidocky
      - CLICKHOUSE_USER=root
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - "CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}"
    networks:
      - main
    volumes:
      - ./clickhouse_db:/var/lib/clickhouse
    restart: always
    ports:
      - "${PORT_CLICKHOUSE}:8123"
      - "${PORT_CLICKHOUSE_POSTGRES}:9005"

  core:
    container_name: okidocky-core
    privileged: true
    build:
      context: ./back
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    restart: always
    network_mode: "host"
    volumes:
      - "/:/rootfs:ro,rslave"
      - "/run/docker.sock:/run/docker.sock:ro,rslave"
      - "./back/target:/app/target"
      - "./back/src:/app/src"
      - "./back/bindings:/app/bindings"
      - "./sqlite_db:/app/sqlite"
    environment:
      - "USERNAME=${USERNAME}"
      - "PASSWORD=${PASSWORD}"
      - "JWT_SECRET=${JWT_SECRET}"
      - "CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}"
      - "PORT_CLICKHOUSE=${PORT_CLICKHOUSE}"
      - "ROCKET_PORT=${PORT_CORE}"

  ui:
    container_name: okidocky-ui
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    depends_on:
      - core
    restart: always
    network_mode: "host"
    volumes:
      - "./front/src:/opt/app/src"
      - "./front/static:/opt/app/static"
    environment:
      - "PORT_CORE=${PORT_CORE}"
      - "PORT=${PORT_UI}"

networks:
  main:
    driver: bridge
