// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerData } from "./ContainerData";

export type ComposeData = { filePath: string, id: string, containers: Array<ContainerData>, };