// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerStatisticsRow } from "./ContainerStatisticsRow";

export type ContainerStatsResponse = { stats: Array<ContainerStatisticsRow>, };