// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContainerPortRebind } from "./ContainerPortRebind";

export type ContainerPortRebindRequest = { ports: Array<ContainerPortRebind>, };