// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NetworkContainerData = { name: string, endpointId: string, macAddress: string, ipv4Address: string, ipv6Address: string, };