// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OurIpamConfig = { subnet: string, ipRange: string, gateway: string, auxAddresses: { [key: string]: string } | null, };