// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkContainers } from "./NetworkContainers";
import type { OurIpamConfig } from "./OurIpamConfig";

export type OurNetwork = { id: string, name: string, created: string, labels: { [key: string]: string } | null, ipamConfig: Array<OurIpamConfig> | null, containers: { [key: string]: NetworkContainers } | null, };