// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OverviewResponse = { versionDocker: string, versionLinux: string, images: number, containers: number, volumes: number, networks: number, };