// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ImageData } from "./ImageData";
import type { TopologyContainer } from "./TopologyContainer";
import type { TopologyPort } from "./TopologyPort";
import type { TopologyVolume } from "./TopologyVolume";

export type Topology = { containers: Array<TopologyContainer>, ports: Array<TopologyPort>, volumes: Array<TopologyVolume>, images: Array<ImageData>, clusters: Array<Array<TopologyContainer>>, };