FROM ubuntu:22.04 AS runtime
RUN apt-get update -y && apt-get install cargo libssl-dev pkg-config gcc g++ libpq-dev libsqlite3-0 libsqlite3-dev -y
RUN cargo install cargo-watch
WORKDIR app
COPY . .
CMD ["cargo", "watch", "-x", "run"]