// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HistoryResponse = { id: string, created: bigint, createdBy: string, tags: Array<string>, size: bigint, comment: string, };