// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryResponse } from "./HistoryResponse";

export type ImageData = { id: string, tags: Array<string>, size: bigint, created: bigint, history: Array<HistoryResponse> | null, };