// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NetworkData } from "./NetworkData";

export type NetworkList = { networks: Array<NetworkData>, };