// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OurPortTypeEnum } from "./OurPortTypeEnum";

export type PortData = { ip: string | null, privatePort: number, publicPort: number | null, type: OurPortTypeEnum | null, };