// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { SimplePortData } from "./SimplePortData";

export type TopologyPort = { data: SimplePortData, connectedTo: Array<string>, position: Position | null, };