// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Position } from "./Position";
import type { VolumeData } from "./VolumeData";

export type TopologyVolume = { data: VolumeData, connectedTo: Array<string>, position: Position | null, };