// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VolumeData = { name: string, createdAt: string, mountpoint: string, size: bigint, isMountpoint: boolean, base64Name: string, };