// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileData } from "./FileData";

export type VolumeExplorerData = { currentFolder: string, directories: Array<FileData>, files: Array<FileData>, };