FROM node:20

WORKDIR /opt/app

COPY package.json /opt/app
COPY package-lock.json /opt/app

RUN npm install

COPY . /opt/app

RUN npm run build

CMD ["npm", "run", "prod", "--", "--host", "--port", "7777"]

